server:
  port: 3344
spring:
  application:
    name: springcloud-config-server
  # 连接远程Git仓库
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/sugarbabyzzz/springcloud-config.git  # https

# 通过 config-server 可以连接到git，访问其中的资源以及配置