spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    # 配置sentinel的dashboard
    sentinel:
      transport:
        dashboard: localhost:8080
      # 使链路限流生效
      filter:
        enabled: false

  application:
    name: provider

server:
  port: 8081

# 将所有请求开放出来
management:
  endpoints:
    web:
      exposure:
        include: '*'

# RocketMQ
rocketmq:
  name-server: 127.0.0.1:9876
  producer:
    group: myprovider
