server:
  port: 8001

# mybatis配置
mybatis:
  type-aliases-package: com.sugar.springcloud.pojo
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:mybatis-config.xml

# spring配置
spring:
  application:
    name: springcloud-provider-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db01?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456

# Eureka配置，配置服务注册到哪里
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/,http://localhost:7002/eureka/,http://localhost:7003/eureka/
  instance:
    instance-id: springcloud-provider-dept-hystrix:8001 # 修改eureka上的默认描述信息
    prefer-ip-address: true  # 显示服务的IP地址，而非localhost

# 配置监控信息
info:
  app.name: sugar-springcloud
  company.name: casia