server:
  port: 7002

# Eureka配置
eureka:
  instance:
    hostname: localhost  # Eureka服务端的实例名称
  client:
    register-with-eureka: false  # 表示是否向eureka注册中心注册自己
    fetch-registry: false  # 如果为false，表示自己为注册中心
    service-url:  # 监控页面，与eureka交互地址
      # 单机：http://${eureka.instance.hostname}:${server.port}/eureka
      # 集群（关联）：挂载7002和7003
      defaultZone: http://localhost:7001/eureka,http://localhost:7003/eureka