spring:
  profiles:
    active: dev

---
server:
  port: 7001

# spring配置
spring:
  profiles: dev
  application:
    name: springcloud-provider-eureka

# Eureka配置
eureka:
  instance:
    hostname: localhost  # Eureka服务端的实例名称
  client:
    register-with-eureka: false  # 表示是否向eureka注册中心注册自己
    fetch-registry: false  # 如果为false，表示自己为注册中心
    service-url:  # 监控页面，与eureka交互地址
      defaultZone: http://localhost:7002/eureka,http://localhost:7003/eureka

---
server:
  port: 7001

# spring配置
spring:
  profiles: dev
  application:
    name: springcloud-provider-eureka

# Eureka配置
eureka:
  instance:
    hostname: localhost  # Eureka服务端的实例名称
  client:
    register-with-eureka: false  # 表示是否向eureka注册中心注册自己
    fetch-registry: false  # 如果为false，表示自己为注册中心
    service-url:  # 监控页面，与eureka交互地址
      defaultZone: http://localhost:7002/eureka,http://localhost:7003/eureka