server:
  port: 9527

spring:
  application:
    name: springcloud-zuul

# eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/,http://localhost:7002/eureka/,http://localhost:7003/eureka/
  instance:
    instance-id: zuul9527.com
    prefer-ip-address: true
info:
  app.name: sugar-springcloud
  company.name: isi

# zuul 隐藏服务名
zuul:
  routes:
    mydept.serviceId: springcloud-provider-dept
    mydept.path: /mydept/**
  ignored-services: "*"  # 隐藏全部的真实服务名
  prefix: /sugar  # 统一的访问前缀